import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header/Header";
import Footer from "@/components/common/footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { FaWhatsapp } from "react-icons/fa6";
import { IoLocationSharp } from "react-icons/io5";

import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Health Vista Diagnostics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />

        {/* WhatsApp Button */}
        <div className="fixed bottom-5 right-5 flex items-center bg-green-500 text-white p-2 rounded-full shadow-lg z-50 hover:bg-green-600 transition duration-300 ease-in-out">
          <Link
            href="https://wa.me/9311883059"
            className="flex items-center font-semibold"
            target="_blank"
          >
            <FaWhatsapp className="text-4xl" />
          </Link>
        </div>

        {/* Location Button - Moved slightly up and left to prevent overlap */}
        <div className="fixed bottom-20 right-5 flex items-center bg-red-500 text-white p-2 rounded-full shadow-lg z-50 hover:bg-red-600 transition duration-300 ease-in-out">
          <Link
            href="https://www.google.com/maps/place/Health+Vista+Diagnostics+-+Best+Diagnostic+centre+in+Pitampura+%7C+Interventional+Radiology+%7C+Cardiology+%7C+ECG+in+Pitampura/@28.700161,77.126535,16z/data=!4m6!3m5!1s0x390d03a69dcf1acd:0x46473ecd32974e35!8m2!3d28.7001605!4d77.1265346!16s%2Fg%2F11y1m4m_hx?hl=en&entry=ttu&g_ep=EgoyMDI0MTAwOS4wIKXMDSoASAFQAw%3D%3D"
            className="flex items-center font-semibold"
            target="_blank"
          >
            <IoLocationSharp className="text-4xl" />
          </Link>
        </div>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
